### ISSUE TITLE
Add 'search' method to enable ticket listing

### ISSUE THREAD

**Issue by aweiteka** [dmranck/ticketutil#39]
Service Now users want to be able to list the tickets they own so they can find the ticket ID they want to edit/comment/close. A `**kwargs` method would probably be the most useful. For example:

    search(assigned_to='foo@example.com')

**Comment by dmranck** [comment]
My gut reaction with this is it's slightly outside the scope of ticketutil, which is meant to be a simpler CRUD (create, read, update, delete) utility. This request falls more into the query-area, which is covered by the following: https://github.com/dmranck/ticketutil/issues/11. Even within CRUD, there's still work to do across all 5 of the supported ticketutil tools.

That being said, we're always open to contributions, and are willing to help! Feel free to fork the repo or open a PR if you make changes you feel would benefit the main ticketutil repo. We do prefer that if a major change is made in one tool (as in querying), the other tools support it as well, so that there's consistency across all of ticketutil.

**Comment by aweiteka** [comment]
Sounds good. I'll close this in favor of #11. Thanks.
